application: cp100-dev2
module: admin
version: alpha-002
runtime: go
api_version: go1
instance_class: B1
manual_scaling:
  instances: 1

handlers:
- url: /.*
  script: _go_app
  login: admin
  secure: always
